name: Update File
on: [push]
# on:
#   schedule:
#     - cron: "0 1 * * *"

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm run example
